### PR TITLE
Adding readme. Bump to 2015

### LINKED ISSUE #3: One Page Documentation
https://github.com/orgs/LabVIEW-DCAF/teams/contributor/repositories

### LINKED ISSUE #7: Clearly Document the Advanced Session Resource API Dependency
This module still needs the API to get a list of resources from a session and open individual connections to each item. 

http://forums.ni.com/t5/NI-Labs-Toolkits/LabVIEW-FPGA-Advanced-Session-Resources/ta-p/3500447

This is also missing a link to LabVIEW 2017. It'd be good to get that fixed or see if the 2016 files happen to work in 17.

### PR DESCRIPTION
**Pull request by agomez08**
Adding readme to document the steps to configure and run this module.
Fixes #3 
Fixes #7

### CODE REVIEW

**Comment by agomez08** [comment]
@jacobson3 @becega 
Do you guys have any insight in why the Jenkins test is not passing?
I only made changes in documentation.

**Comment by jacobson3** [comment]
@agomezNI 
It looks like the package build failed. I attached the error report. It looks to me like you might just want to try a mass compile in 2014 SP1.

[BuildErrors.txt](https://github.com/LabVIEW-DCAF/FPGA-Module/files/3065523/BuildErrors.txt)

**Comment by agomez08** [comment]
Just mass compiled source to LV 2015. Updated Jenkinsfile and VIPB to 15.0 as well.

Also changed editor code to correctly load RIO Resource field from file. Fixes #12 

FYI @jacobson3 @becega , should we do anything to trigger the analysis and build again?

**Comment by agomez08** [comment]
@becega Build continues failing. Not sure how the built passed in the previous release. I noticed that in the project they have added a cRIO and the classes are underneath.

**Comment by becega** [comment]
@agomezNI the build was failing because the build node didn't have the advance FGPA session installed.  https://forums.ni.com/t5/NI-Labs-Toolkits/LabVIEW-FPGA-Advanced-Session-Resources/ta-p/3500447?profile.language=en

**Review by becega — APPROVED** [review]
Looks good. thanks

**Pull request merged**
