### PR TITLE
Editor ui improvements 5 6 9

### PR DESCRIPTION
**Pull request by jacobson3**
A few minor editor improvements

- GetText.vi override was updated to use FPGA_target.png glyph (the glyph used for FPGA targets in the projecet explorer) and it's name was set to "FPGA Module" which was previously "FPGA Module Configuration"
- Updated permissions control files to now be "Read from FPGA" and "Write to FPGA" which were previously "Read from HW" and "Write to HW"

### CODE REVIEW

**Comment by pollockm** [comment]
@theSloopJohnB - this is the commit that diff is failing on.  Possibly related to the very large number of files to diff at once.

**Comment by jbellamyNI** [comment]
I built in the workaround, but this build was hanging due to LabVIEW getting caught on an 'Ignore updated file paths' (or whatever it's called) dialog.

**Comment by theSloopJohnB** [comment]
Fun. Can you file an issue to buildsystem about that so we can track it for the diff tool?


On Oct 31, 2017, at 1:58 PM, jbellamyNI <notifications@github.com<mailto:notifications@github.com>> wrote:


I built in the workaround, but this build was hanging due to LabVIEW getting caught on an 'Ignore updated file paths' (or whatever it's called) dialog.

**Comment by jacobson3** [comment]
@jbellamyNI / @Beazurt 
Will either of you have time to review this in the next week or so? Most every VI edit was due to separating source from compiled code so VIs don't keep getting flagged for edits and only two VIs should have actually been modified. Let me know if you won't have any time and I can try to get another person to review it.

**Comment by jbellamyNI** [comment]
I honestly have zero familiarity with this code base. The changes I made were to the build system.

**Review by becega — APPROVED** [review]
Looks good for changes like this, if it happens again is better to make 2 different commits one for the change in the separate from source, and one for the actual changes.

**Pull request merged**
